### ISSUE TITLE
Add Initial Next.js Frontend Project Structure to CertifyHub

### ISSUE THREAD

**Issue by satyamsharma17** [Code4All-Club/CertifyHub#3]
#### Description:
We need to establish a basic Next.js frontend project structure for the CertifyHub application. This will provide the client-side component, allowing users to interact with our platform efficiently.

#### Tasks:
- Set up the initial folder structure for the Next.js frontend project.

#### Acceptance Criteria:
- The initial Next.js project structure is created as outlined above.
- All necessary files are initialized and properly configured.

#### Additional Notes:
- Ensure that the Next.js project is configured to communicate with the backend services efficiently.
- Follow best practices for file organization and coding standards.

**Comment by Pragyaa3** [comment]
@satyamsharma17 Please assign this issue to me.
