### ISSUE TITLE
Add `blockchain` Folder Structure

### ISSUE THREAD

**Issue by satyamsharma17** [Code4All-Club/CertifyHub#7]
**Description**  
To support blockchain integration in CertifyHub, we need to add a `blockchain` folder with the appropriate structure and necessary files. This folder will contain smart contracts, deployment scripts, and utility functions to facilitate blockchain functionality within the project.

**Proposed Folder Structure**  

```
CertifyHub/
├── blockchain/
│   ├── contracts/            # Contains smart contracts (e.g., Solidity files)
│   ├── scripts/              # Deployment and interaction scripts
│   ├── utils/                # Helper functions for blockchain operations
│   ├── config/               # Configuration files (e.g., network settings)
│   └── README.md             # Instructions and documentation for blockchain setup
```

**Acceptance Criteria**  
- [ ] Create the `blockchain` folder with the specified structure.
- [ ] Add a `README.md` file in the `blockchain` folder to document instructions for blockchain setup.
- [ ] Ensure placeholder files (such as `.gitkeep`) are added to empty folders so they are tracked by Git.
- [ ] Outline the purpose of each folder and instructions for using smart contracts, scripts, and utility functions in `README.md`.

**Additional Context**  
This structure will help maintain organization and provide clear guidance for contributors who work on the blockchain component of CertifyHub.

**Comment by Deshmukh-Ayush** [comment]
@satyamsharma17 Please assign this issue to me.
